// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sbc.Infrastructure.Persistence;

#nullable disable

namespace Sbc.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SbcDbContext))]
    partial class SbcDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sbc.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid?>("ProtectedSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("protected_system_id");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_alerts_code");

                    b.HasIndex("ProtectedSystemId")
                        .HasDatabaseName("ix_alerts_protected_system_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_alerts_status");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("Sbc.Domain.Entities.BackupEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BackupJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("backup_job_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("event_type");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid?>("ProtectedSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("protected_system_id");

                    b.Property<string>("RawPayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("raw_payload_json");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("severity");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_backup_events");

                    b.HasIndex("BackupJobId")
                        .HasDatabaseName("ix_backup_events_backup_job_id");

                    b.HasIndex("ProtectedSystemId")
                        .HasDatabaseName("ix_backup_events_protected_system_id");

                    b.ToTable("backup_events", (string)null);
                });

            modelBuilder.Entity("Sbc.Domain.Entities.BackupJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BackupPath")
                        .HasColumnType("text")
                        .HasColumnName("backup_path");

                    b.Property<string>("BackupType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("backup_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at_utc");

                    b.Property<Guid>("ProtectedSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("protected_system_id");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UrBackupJobId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ur_backup_job_id");

                    b.HasKey("Id")
                        .HasName("pk_backup_jobs");

                    b.HasIndex("ProtectedSystemId")
                        .HasDatabaseName("ix_backup_jobs_protected_system_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_backup_jobs_status");

                    b.ToTable("backup_jobs", (string)null);
                });

            modelBuilder.Entity("Sbc.Domain.Entities.ManualBackupRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("assigned_to");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("ProtectedSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("protected_system_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("RelatedChangeReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("related_change_reference");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at_utc");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<DateTime?>("ValidatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_at_utc");

                    b.Property<string>("ValidatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("validated_by");

                    b.Property<string>("ValidationNotes")
                        .HasColumnType("text")
                        .HasColumnName("validation_notes");

                    b.HasKey("Id")
                        .HasName("pk_manual_backup_requests");

                    b.HasIndex("ProtectedSystemId")
                        .HasDatabaseName("ix_manual_backup_requests_protected_system_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_manual_backup_requests_status");

                    b.ToTable("manual_backup_requests", (string)null);
                });

            modelBuilder.Entity("Sbc.Domain.Entities.ProtectedSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BackupCapability")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("backup_capability");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Criticality")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("criticality");

                    b.Property<bool>("FileBackupValidated")
                        .HasColumnType("boolean")
                        .HasColumnName("file_backup_validated");

                    b.Property<string>("FileSystem")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("file_system");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("hostname");

                    b.Property<bool>("ImageBackupValidated")
                        .HasColumnType("boolean")
                        .HasColumnName("image_backup_validated");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_online");

                    b.Property<DateTime?>("LastFileBackupAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_file_backup_at_utc");

                    b.Property<int?>("LastFileBackupIssues")
                        .HasColumnType("integer")
                        .HasColumnName("last_file_backup_issues");

                    b.Property<bool>("LastFileBackupOk")
                        .HasColumnType("boolean")
                        .HasColumnName("last_file_backup_ok");

                    b.Property<DateTime?>("LastImageBackupAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_image_backup_at_utc");

                    b.Property<bool>("LastImageBackupOk")
                        .HasColumnType("boolean")
                        .HasColumnName("last_image_backup_ok");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<bool>("LiveBackupValidated")
                        .HasColumnType("boolean")
                        .HasColumnName("live_backup_validated");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operating_system");

                    b.Property<string>("PartitionScheme")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("partition_scheme");

                    b.Property<Guid?>("SimulatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("simulator_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UrBackupClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ur_backup_client_id");

                    b.Property<string>("UrBackupClientName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("ur_backup_client_name");

                    b.Property<string>("UrBackupClientVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ur_backup_client_version");

                    b.Property<int?>("UrBackupStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("ur_backup_status_code");

                    b.HasKey("Id")
                        .HasName("pk_protected_systems");

                    b.HasIndex("Hostname")
                        .HasDatabaseName("ix_protected_systems_hostname");

                    b.HasIndex("IsOnline")
                        .HasDatabaseName("ix_protected_systems_is_online");

                    b.HasIndex("LastSeenAtUtc")
                        .HasDatabaseName("ix_protected_systems_last_seen_at_utc");

                    b.HasIndex("SimulatorId")
                        .HasDatabaseName("ix_protected_systems_simulator_id");

                    b.HasIndex("UrBackupClientId")
                        .HasDatabaseName("ix_protected_systems_ur_backup_client_id");

                    b.ToTable("protected_systems", (string)null);
                });

            modelBuilder.Entity("Sbc.Domain.Entities.Simulator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_simulators");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_simulators_code");

                    b.ToTable("simulators", (string)null);
                });

            modelBuilder.Entity("Sbc.Domain.Entities.Alert", b =>
                {
                    b.HasOne("Sbc.Domain.Entities.ProtectedSystem", "ProtectedSystem")
                        .WithMany("Alerts")
                        .HasForeignKey("ProtectedSystemId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_alerts_protected_systems_protected_system_id");

                    b.Navigation("ProtectedSystem");
                });

            modelBuilder.Entity("Sbc.Domain.Entities.BackupEvent", b =>
                {
                    b.HasOne("Sbc.Domain.Entities.BackupJob", "BackupJob")
                        .WithMany("Events")
                        .HasForeignKey("BackupJobId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_backup_events_backup_jobs_backup_job_id");

                    b.HasOne("Sbc.Domain.Entities.ProtectedSystem", "ProtectedSystem")
                        .WithMany("BackupEvents")
                        .HasForeignKey("ProtectedSystemId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_backup_events_protected_systems_protected_system_id");

                    b.Navigation("BackupJob");

                    b.Navigation("ProtectedSystem");
                });

            modelBuilder.Entity("Sbc.Domain.Entities.BackupJob", b =>
                {
                    b.HasOne("Sbc.Domain.Entities.ProtectedSystem", "ProtectedSystem")
                        .WithMany("BackupJobs")
                        .HasForeignKey("ProtectedSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_backup_jobs_protected_systems_protected_system_id");

                    b.Navigation("ProtectedSystem");
                });

            modelBuilder.Entity("Sbc.Domain.Entities.ManualBackupRequest", b =>
                {
                    b.HasOne("Sbc.Domain.Entities.ProtectedSystem", "ProtectedSystem")
                        .WithMany()
                        .HasForeignKey("ProtectedSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_manual_backup_requests_protected_systems_protected_system_id");

                    b.Navigation("ProtectedSystem");
                });

            modelBuilder.Entity("Sbc.Domain.Entities.ProtectedSystem", b =>
                {
                    b.HasOne("Sbc.Domain.Entities.Simulator", "Simulator")
                        .WithMany("Systems")
                        .HasForeignKey("SimulatorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_protected_systems_simulators_simulator_id");

                    b.Navigation("Simulator");
                });

            modelBuilder.Entity("Sbc.Domain.Entities.BackupJob", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Sbc.Domain.Entities.ProtectedSystem", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("BackupEvents");

                    b.Navigation("BackupJobs");
                });

            modelBuilder.Entity("Sbc.Domain.Entities.Simulator", b =>
                {
                    b.Navigation("Systems");
                });
#pragma warning restore 612, 618
        }
    }
}
