import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { sbcApi } from '../api/sbcApi';
import { EmptyState } from '../components/EmptyState';
import { StatusBadge } from '../components/StatusBadge';
import { SummaryCard } from '../components/SummaryCard';
import type { OpenAlert } from '../types/dashboard';
import { formatDateTime } from '../utils/formatters';

type AlertFilter = 'all' | 'open' | 'resolved';

export function AlertsPage() {
  const [alerts, setAlerts] = useState<OpenAlert[]>([]);
  const [filter, setFilter] = useState<AlertFilter>('open');
  const [searchText, setSearchText] = useState('');
  const [resolvingAlertId, setResolvingAlertId] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  async function loadAlerts() {
    try {
      setIsLoading(true);
      setErrorMessage(null);

      const response = await sbcApi.get<OpenAlert[]>('/alerts');

      setAlerts(response.data);
    } catch (error) {
      console.error(error);
      setErrorMessage('Could not load alerts.');
    } finally {
      setIsLoading(false);
    }
  }

  async function resolveAlert(alertId: string) {
    try {
      setResolvingAlertId(alertId);
      setErrorMessage(null);

      await sbcApi.post(`/alerts/${alertId}/resolve`);

      await loadAlerts();
    } catch (error) {
      console.error(error);
      setErrorMessage('Could not resolve alert.');
    } finally {
      setResolvingAlertId(null);
    }
  }

  useEffect(() => {
    loadAlerts();
  }, []);

  const filteredAlerts = useMemo(() => {
    const normalizedSearchText = searchText.trim().toLowerCase();

    return alerts.filter((alert) => {
      const normalizedStatus = alert.status.toLowerCase();

      const matchesFilter =
        filter === 'all' ||
        (filter === 'open' && normalizedStatus === 'open') ||
        (filter === 'resolved' && normalizedStatus === 'resolved');

      const searchableValues = [
        alert.title,
        alert.code,
        alert.message,
        alert.severity,
        alert.status,
        alert.protectedSystem?.hostname,
        alert.protectedSystem?.operatingSystem,
        alert.protectedSystem?.ipAddress,
        alert.protectedSystem?.simulator?.name,
      ]
        .filter((value): value is string => Boolean(value))
        .map((value) => value.toLowerCase());

      const matchesSearch =
        normalizedSearchText.length === 0 ||
        searchableValues.some((value) => value.includes(normalizedSearchText));

      return matchesFilter && matchesSearch;
    });
  }, [alerts, filter, searchText]);

  const openCount = alerts.filter((alert) => alert.status === 'Open').length;
  const resolvedCount = alerts.filter((alert) => alert.status === 'Resolved').length;
  const warningCount = alerts.filter((alert) => alert.severity === 'Warning').length;
  const criticalCount = alerts.filter((alert) => alert.severity === 'Critical').length;

  return (
    <div className="page-shell">
      <header className="page-title-row">
        <div>
          <h2>Alerts</h2>
          <p>Open and resolved backup alerts generated by SBC monitoring.</p>
        </div>

        <button
          className="primary-button"
          type="button"
          onClick={loadAlerts}
          disabled={isLoading}
        >
          {isLoading ? 'Refreshing...' : 'Refresh'}
        </button>
      </header>

      {errorMessage && (
        <section className="error-card">
          {errorMessage}
        </section>
      )}

      <section className="summary-grid">
        <SummaryCard
          title="Open"
          value={openCount}
          description="Active alerts"
          variant={openCount > 0 ? 'danger' : 'default'}
        />

        <SummaryCard
          title="Resolved"
          value={resolvedCount}
          description="Closed alerts"
        />

        <SummaryCard
          title="Warnings"
          value={warningCount}
          description="Warning severity alerts"
          variant={warningCount > 0 ? 'warning' : 'default'}
        />

        <SummaryCard
          title="Critical"
          value={criticalCount}
          description="Critical severity alerts"
          variant={criticalCount > 0 ? 'danger' : 'default'}
        />
      </section>

      <section className="dashboard-section">
        <div className="section-header">
          <div>
            <h3>Alert list</h3>
            <p>Filter, inspect and resolve active backup alerts.</p>
          </div>

          <span className="section-count">
            {filteredAlerts.length}
          </span>
        </div>

        <div className="filters-row">
          <input
            className="filter-input"
            type="search"
            placeholder="Search by title, code, message, system, simulator or OS..."
            value={searchText}
            onChange={(event) => setSearchText(event.target.value)}
          />

          <select
            className="filter-select"
            value={filter}
            onChange={(event) => setFilter(event.target.value as AlertFilter)}
          >
            <option value="open">Open alerts</option>
            <option value="resolved">Resolved alerts</option>
            <option value="all">All alerts</option>
          </select>
        </div>

        {isLoading && alerts.length === 0 ? (
          <section className="status-card">
            Loading alerts...
          </section>
        ) : (
          <AlertsTable
            alerts={filteredAlerts}
            resolvingAlertId={resolvingAlertId}
            onResolveAlert={resolveAlert}
          />
        )}
      </section>
    </div>
  );
}

type AlertsTableProps = {
  alerts: OpenAlert[];
  resolvingAlertId: string | null;
  onResolveAlert: (alertId: string) => void;
};

function AlertsTable({
  alerts,
  resolvingAlertId,
  onResolveAlert,
}: AlertsTableProps) {
  if (alerts.length === 0) {
    return (
      <EmptyState message="No alerts match the selected filters." />
    );
  }

  return (
    <div className="table-wrapper">
      <table className="data-table">
        <thead>
          <tr>
            <th>Alert</th>
            <th>Severity</th>
            <th>Status</th>
            <th>System</th>
            <th>Created</th>
            <th>Resolved</th>
            <th>Message</th>
            <th>Action</th>
          </tr>
        </thead>

        <tbody>
          {alerts.map((alert) => (
            <tr key={alert.id}>
              <td>
                <strong>{alert.title}</strong>
                <span>{formatAlertCode(alert.code)}</span>
              </td>

              <td>
                <StatusBadge value={alert.severity} />
              </td>

              <td>
                <StatusBadge value={alert.status} />
              </td>

              <td>
                {alert.protectedSystem ? (
                  <>
                    <strong>{alert.protectedSystem.hostname}</strong>
                    <span>{alert.protectedSystem.operatingSystem ?? 'Unknown OS'}</span>

                    {alert.protectedSystem.simulator && (
                      <span>{alert.protectedSystem.simulator.name}</span>
                    )}

                    <Link
                      className="inline-link"
                      to={`/systems/${alert.protectedSystem.id}`}
                    >
                      View system
                    </Link>
                  </>
                ) : (
                  <>
                    <strong>General alert</strong>
                    <span>No system assigned</span>
                  </>
                )}
              </td>

              <td>
                {formatDateTime(alert.createdAtUtc)}
              </td>

              <td>
                {formatDateTime(alert.resolvedAtUtc)}
              </td>

              <td>
                <span className="alert-message">
                  {alert.message}
                </span>
              </td>

              <td>
                {alert.status === 'Open' ? (
                  <button
                    className="table-action-button"
                    type="button"
                    onClick={() => onResolveAlert(alert.id)}
                    disabled={resolvingAlertId === alert.id}
                  >
                    {resolvingAlertId === alert.id ? 'Resolving...' : 'Resolve'}
                  </button>
                ) : (
                  <span className="muted-text">
                    No action
                  </span>
                )}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function formatAlertCode(value: string) {
  return value
    .toLowerCase()
    .replace(/_/g, ' ')
    .replace(/^./, (firstLetter) => firstLetter.toUpperCase());
}